version: 2.1
jobs:

  build:
    docker:
      - image: thomasweise/texlive
    steps:
      - checkout
      - run:
          name: Compile
          command: make
      - run:
          name: Move artifacts
          command: |
            mkdir -p results
            mv resume/resume.pdf results/
            mv VERSION results/
            mv resume/coverletter.pdf results/
            mv Makefile results/
      - persist_to_workspace:
          root: results
          paths:
            - resume.pdf
            - VERSION
            - coverletter.pdf
            - Makefile

  publish-github-release:
      docker:
        - image: cibuilds/github:0.10
      steps:
        - attach_workspace:
            at: results
        - run:
            name: "Publish Release on GitHub"
            command: cd /root/projects/results && make git_push

workflows:
  version: 2
  build:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
