general:
    branches:
        only: master
jobs:
  build:
    docker:
      # Primary container
      - image: thomasweise/texlive
    steps:
      - checkout
      - run:
          name: Compile
          command: make
      - run:
          name: Move artifacts
          command: |
            mkdir -p ~/results
            #mv re/cv.pdf ~/results
            mv resume/resume.pdf ~/results
            mv resume/coverletter.pdf ~/results
      - store_artifacts:
          path: ~/results
