version: 2.1
jobs:

  build:
    docker:
      - image: thomasweise/texlive
    steps:
      - checkout
      - run:
          name: Compile
          command: make

workflows:
  version: 2
  build:
    jobs:
      - build
