version: 2.1
jobs:

  build:
    docker:
      - image: thomasweise/texlive
    steps:
      - checkout
      - run:
          name: Compile
          command: make
      - run:
          name: Move artifacts
          command: |
            mkdir -p ~/results
            mv resume/resume.pdf ~/results
            mv VERSION ~/results
            mv resume/coverletter.pdf ~/results
      - store_artifacts:
          path: ~/results

  publish-github-release:
      docker:
        - image: cibuilds/github:0.10
      steps:
        - attach_workspace:
            at: ~/results
        - run:
            name: "Publish Release on GitHub"
            command: |
              VERSION=$(cat VERSION)
              ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} \
              -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} \
              -delete ${VERSION} ~/results/

workflows:
  version: 2
  build:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
